{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"Oops...we found an error preparing this test file:\n\n  > cypress/e2e/examples/crashed.cy.js\n\n","children":[{"name":"Oops...we found an error preparing this test file: cypress/e2e/examples/crashed.cy.js","uid":"fba3c84fed588705","parentUid":"a9f1ac62274ca1de50f525b9450dd606","status":"broken","time":{"start":1662780868316,"stop":1662780868316,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"Oops...we found an error preparing this test file: cypress/e2e/examples/crashed.cy.js","uid":"c5f82300bee2a78a","parentUid":"a9f1ac62274ca1de50f525b9450dd606","status":"broken","time":{"start":1662780902775,"stop":1662780902775,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"a9f1ac62274ca1de50f525b9450dd606"}],"uid":"bdbf199525818fae7a8651db9eafe741"},{"name":"Product defects","children":[{"name":"Timed out retrying after 4000ms: expected true to equal false","children":[{"name":"should be failed","uid":"74a48330356e1653","parentUid":"dbf7b3a653cc3263c669a04df1239913","status":"failed","time":{"start":1662780918356,"stop":1662780922474,"duration":4118},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[]}],"uid":"dbf7b3a653cc3263c669a04df1239913"},{"name":"The following error originated from your test code, not from Cypress.\n\n  > Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","children":[{"name":"An uncaught error was detected outside of a test","uid":"7c9db9350fb75896","parentUid":"7be34d3fab0658dd8a002b0fb843a5d3","status":"failed","time":{"start":1662780930605,"stop":1662780930743,"duration":138},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"7be34d3fab0658dd8a002b0fb843a5d3"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}],"name":"categories"}